CREATE TABLE WeatherData (
    id INT AUTO_INCREMENT PRIMARY KEY,
    LocalObservationDateTime DATETIME,
    WeatherText VARCHAR(255),
    WeatherIcon INT,
    HasPrecipitation BOOLEAN,
    IsDayTime BOOLEAN,
    Temperature_Value FLOAT,
    Temperature_Unit VARCHAR(10),
    RealFeelTemperature_Value FLOAT,
    RealFeelTemperature_Unit VARCHAR(10),
    RelativeHumidity INT,
    DewPoint_Value FLOAT,
    DewPoint_Unit VARCHAR(10),
    Wind_DirectionDegrees INT,
    Wind_DirectionLocalized VARCHAR(50),
    Wind_Speed_Value FLOAT,
    Wind_Speed_Unit VARCHAR(10),
    UVIndex INT,
    Visibility_Value FLOAT,
    Visibility_Unit VARCHAR(10),
    CloudCover INT,
    Pressure_Value FLOAT,
    Pressure_Unit VARCHAR(10),
    MobileLink VARCHAR(255),
    Link VARCHAR(255)
);
